import { type Alert, AlertState, AlertSeverity } from "./alert.type";

const SAMPLE_ALERTS: Alert[] = [
  { id: 1, title: "Suspicious Email Attachment", severity: AlertSeverity.Medium, state: AlertState.New, age: "2 hours" },
  { id: 2, title: "Failed Login Attempts", severity: AlertSeverity.Low, state: AlertState.Triage, age: "5 hours" },
  { id: 3, title: "Unauthorized Access to Database", severity: AlertSeverity.Critical, state: AlertState.Investigating, age: "1 day" },
  { id: 4, title: "Malware Detection", severity: AlertSeverity.High, state: AlertState.Escalated, age: "6 hours" },
  { id: 5, title: "Unusual Network Traffic", severity: AlertSeverity.Medium, state: AlertState.Review, age: "3 days" },
  { id: 6, title: "Data Exfiltration Attempt", severity: AlertSeverity.Critical, state: AlertState.Investigating, age: "12 hours" },
  { id: 7, title: "Phishing Campaign", severity: AlertSeverity.High, state: AlertState.Triage, age: "4 hours" },
  { id: 8, title: "Ransomware Detection", severity: AlertSeverity.Critical, state: AlertState.Escalated, age: "1 hour" },
  { id: 9, title: "Suspicious Process Execution", severity: AlertSeverity.Medium, state: AlertState.New, age: "30 minutes" },
  { id: 10, title: "Firewall Configuration Change", severity: AlertSeverity.Low, state: AlertState.Review, age: "2 days" },
  { id: 11, title: "Privilege Escalation", severity: AlertSeverity.High, state: AlertState.Investigating, age: "8 hours" },
  { id: 12, title: "DDoS Attack", severity: AlertSeverity.Critical, state: AlertState.Escalated, age: "45 minutes" },
  { id: 13, title: "Unpatched System Vulnerability", severity: AlertSeverity.Medium, state: AlertState.Triage, age: "1 day" },
  { id: 14, title: "Unauthorized Admin Login", severity: AlertSeverity.Critical, state: AlertState.Investigating, age: "3 hours" },
  { id: 15, title: "Data Breach", severity: AlertSeverity.Critical, state: AlertState.Escalated, age: "2 hours" },
  { id: 16, title: "Suspicious File Download", severity: AlertSeverity.Medium, state: AlertState.New, age: "1 hour" },
  { id: 17, title: "Password Policy Violation", severity: AlertSeverity.Low, state: AlertState.Review, age: "5 days" },
  { id: 18, title: "Antivirus Alert", severity: AlertSeverity.Medium, state: AlertState.Triage, age: "3 hours" },
  { id: 19, title: "SSH Brute Force Attempt", severity: AlertSeverity.High, state: AlertState.Investigating, age: "7 hours" },
  { id: 20, title: "Social Engineering Attempt", severity: AlertSeverity.Medium, state: AlertState.New, age: "1 day" },
  { id: 21, title: "Unauthorized File Access", severity: AlertSeverity.High, state: AlertState.Investigating, age: "2 days" },
  { id: 22, title: "Abnormal User Behavior", severity: AlertSeverity.Medium, state: AlertState.Triage, age: "6 hours" },
  { id: 23, title: "Exposed API Key", severity: AlertSeverity.High, state: AlertState.Review, age: "1 day" },
  { id: 24, title: "Man-in-the-Middle Attack", severity: AlertSeverity.Critical, state: AlertState.Escalated, age: "4 hours" },
  { id: 25, title: "Misconfigured S3 Bucket", severity: AlertSeverity.Medium, state: AlertState.Investigating, age: "2 days" },
  { id: 26, title: "Web Application Vulnerability", severity: AlertSeverity.High, state: AlertState.Review, age: "3 days" },
  { id: 27, title: "Suspicious Email Forward Rule", severity: AlertSeverity.Medium, state: AlertState.New, age: "5 hours" },
  { id: 28, title: "Cryptomining Detection", severity: AlertSeverity.High, state: AlertState.Investigating, age: "10 hours" },
  { id: 29, title: "Outdated SSL Certificate", severity: AlertSeverity.Low, state: AlertState.Closed, age: "7 days" },
  { id: 30, title: "Unauthorized Device Connection", severity: AlertSeverity.Medium, state: AlertState.Triage, age: "1 day" },
  { id: 31, title: "Insider Threat Detection", severity: AlertSeverity.Critical, state: AlertState.Escalated, age: "6 hours" },
  { id: 32, title: "Suspicious PowerShell Command", severity: AlertSeverity.High, state: AlertState.Investigating, age: "8 hours" },
  { id: 33, title: "SQL Injection Attempt", severity: AlertSeverity.Critical, state: AlertState.Review, age: "1 day" },
  { id: 34, title: "Software License Violation", severity: AlertSeverity.Low, state: AlertState.Closed, age: "10 days" },
  { id: 35, title: "Remote Access Trojan", severity: AlertSeverity.Critical, state: AlertState.Investigating, age: "5 hours" },
  { id: 36, title: "DNS Cache Poisoning", severity: AlertSeverity.High, state: AlertState.Escalated, age: "1 day" },
  { id: 37, title: "Unauthorized Configuration Change", severity: AlertSeverity.Medium, state: AlertState.Review, age: "2 days" },
  { id: 38, title: "Cross-site Scripting Attack", severity: AlertSeverity.High, state: AlertState.Investigating, age: "12 hours" },
  { id: 39, title: "Weak Encryption Usage", severity: AlertSeverity.Medium, state: AlertState.Triage, age: "3 days" },
  { id: 40, title: "Credential Harvesting", severity: AlertSeverity.High, state: AlertState.New, age: "2 hours" },
  { id: 41, title: "LDAP Injection Attempt", severity: AlertSeverity.High, state: AlertState.Investigating, age: "7 hours" },
  { id: 42, title: "Unauthorized Cloud Resource", severity: AlertSeverity.Medium, state: AlertState.Triage, age: "1 day" },
  { id: 43, title: "Broken Authentication", severity: AlertSeverity.High, state: AlertState.Review, age: "2 days" },
  { id: 44, title: "Zero-day Vulnerability", severity: AlertSeverity.Critical, state: AlertState.Escalated, age: "3 hours" },
  { id: 45, title: "Insecure Direct Object Reference", severity: AlertSeverity.Medium, state: AlertState.New, age: "4 hours" },
  { id: 46, title: "Security Misconfiguration", severity: AlertSeverity.Medium, state: AlertState.Triage, age: "1 day" },
  { id: 47, title: "Command Injection", severity: AlertSeverity.High, state: AlertState.Investigating, age: "6 hours" },
  { id: 48, title: "Improper Access Control", severity: AlertSeverity.Medium, state: AlertState.Review, age: "2 days" },
  { id: 49, title: "Session Hijacking", severity: AlertSeverity.High, state: AlertState.Escalated, age: "5 hours" },
  { id: 50, title: "XML External Entity Attack", severity: AlertSeverity.Medium, state: AlertState.Investigating, age: "1 day" },
  { id: 51, title: "Insecure Deserialization", severity: AlertSeverity.High, state: AlertState.Triage, age: "8 hours" },
  { id: 52, title: "Insufficient Logging", severity: AlertSeverity.Low, state: AlertState.Closed, age: "5 days" },
  { id: 53, title: "Suspicious File Upload", severity: AlertSeverity.Medium, state: AlertState.New, age: "3 hours" },
  { id: 54, title: "Component with Known Vulnerability", severity: AlertSeverity.Medium, state: AlertState.Review, age: "2 days" },
  { id: 55, title: "Broken Access Control", severity: AlertSeverity.High, state: AlertState.Investigating, age: "1 day" },
  { id: 56, title: "Missing Security Headers", severity: AlertSeverity.Low, state: AlertState.Closed, age: "6 days" },
  { id: 57, title: "CSRF Attack", severity: AlertSeverity.Medium, state: AlertState.Triage, age: "7 hours" },
  { id: 58, title: "Server-Side Request Forgery", severity: AlertSeverity.High, state: AlertState.Investigating, age: "9 hours" },
  { id: 59, title: "Buffer Overflow", severity: AlertSeverity.Critical, state: AlertState.Escalated, age: "2 hours" },
  { id: 60, title: "Unencrypted Data Transfer", severity: AlertSeverity.Medium, state: AlertState.Review, age: "3 days" },
  { id: 61, title: "Vulnerable Dependency", severity: AlertSeverity.Medium, state: AlertState.New, age: "4 hours" },
  { id: 62, title: "Hardcoded Credentials", severity: AlertSeverity.High, state: AlertState.Investigating, age: "1 day" },
  { id: 63, title: "API Abuse", severity: AlertSeverity.Medium, state: AlertState.Triage, age: "5 hours" },
  { id: 64, title: "Unauthorized Port Scanning", severity: AlertSeverity.Low, state: AlertState.Review, age: "2 days" },
  { id: 65, title: "Suspicious Registry Change", severity: AlertSeverity.Medium, state: AlertState.New, age: "6 hours" },
  { id: 66, title: "Memory Leak", severity: AlertSeverity.Low, state: AlertState.Closed, age: "8 days" },
  { id: 67, title: "HTTP Response Splitting", severity: AlertSeverity.Medium, state: AlertState.Investigating, age: "1 day" },
  { id: 68, title: "Open Redirect", severity: AlertSeverity.Low, state: AlertState.Triage, age: "3 days" },
  { id: 69, title: "Path Traversal", severity: AlertSeverity.High, state: AlertState.Escalated, age: "7 hours" },
  { id: 70, title: "File Inclusion Vulnerability", severity: AlertSeverity.High, state: AlertState.Investigating, age: "10 hours" },
  { id: 71, title: "Race Condition", severity: AlertSeverity.Medium, state: AlertState.Review, age: "2 days" },
  { id: 72, title: "Information Disclosure", severity: AlertSeverity.Medium, state: AlertState.New, age: "5 hours" },
  { id: 73, title: "Clickjacking Vulnerability", severity: AlertSeverity.Low, state: AlertState.Closed, age: "7 days" },
  { id: 74, title: "Unvalidated Redirects", severity: AlertSeverity.Medium, state: AlertState.Triage, age: "1 day" },
  { id: 75, title: "Cache Poisoning", severity: AlertSeverity.High, state: AlertState.Investigating, age: "8 hours" },
  { id: 76, title: "OS Command Injection", severity: AlertSeverity.Critical, state: AlertState.Escalated, age: "3 hours" },
  { id: 77, title: "Unprotected API Endpoint", severity: AlertSeverity.High, state: AlertState.Review, age: "2 days" },
  { id: 78, title: "Integer Overflow", severity: AlertSeverity.Medium, state: AlertState.Triage, age: "1 day" },
  { id: 79, title: "Business Logic Vulnerability", severity: AlertSeverity.Medium, state: AlertState.New, age: "4 hours" },
  { id: 80, title: "Host Header Injection", severity: AlertSeverity.Medium, state: AlertState.Investigating, age: "9 hours" },
  { id: 81, title: "Insecure Cryptographic Storage", severity: AlertSeverity.High, state: AlertState.Escalated, age: "1 day" },
  { id: 82, title: "LDAP Server Misconfiguration", severity: AlertSeverity.Medium, state: AlertState.Review, age: "3 days" },
  { id: 83, title: "Security Log Tampering", severity: AlertSeverity.Critical, state: AlertState.Investigating, age: "5 hours" },
  { id: 84, title: "Format String Vulnerability", severity: AlertSeverity.Medium, state: AlertState.New, age: "2 hours" },
  { id: 85, title: "Improper Certificate Validation", severity: AlertSeverity.High, state: AlertState.Triage, age: "1 day" },
  { id: 86, title: "WebSocket Hijacking", severity: AlertSeverity.Medium, state: AlertState.Investigating, age: "6 hours" },
  { id: 87, title: "Mass Assignment", severity: AlertSeverity.Medium, state: AlertState.Review, age: "2 days" },
  { id: 88, title: "Subdomain Takeover", severity: AlertSeverity.High, state: AlertState.Escalated, age: "8 hours" },
  { id: 89, title: "Expired Domain Hijacking", severity: AlertSeverity.Medium, state: AlertState.Triage, age: "1 day" },
  { id: 90, title: "JWT Token Manipulation", severity: AlertSeverity.High, state: AlertState.Investigating, age: "7 hours" },
  { id: 91, title: "Content Security Policy Bypass", severity: AlertSeverity.Medium, state: AlertState.New, age: "3 hours" },
  { id: 92, title: "XML Bomb", severity: AlertSeverity.Medium, state: AlertState.Review, age: "2 days" },
  { id: 93, title: "Parameter Pollution", severity: AlertSeverity.Low, state: AlertState.Closed, age: "9 days" },
  { id: 94, title: "Authentication Bypass", severity: AlertSeverity.Critical, state: AlertState.Escalated, age: "4 hours" },
  { id: 95, title: "Forced Browsing", severity: AlertSeverity.Medium, state: AlertState.Investigating, age: "1 day" },
  { id: 96, title: "Client-Side Template Injection", severity: AlertSeverity.Medium, state: AlertState.Triage, age: "5 hours" },
  { id: 97, title: "DOM-based XSS", severity: AlertSeverity.High, state: AlertState.Review, age: "2 days" },
  { id: 98, title: "Server-Side Template Injection", severity: AlertSeverity.Critical, state: AlertState.Investigating, age: "6 hours" },
  { id: 99, title: "CRLF Injection", severity: AlertSeverity.Medium, state: AlertState.New, age: "4 hours" },
  { id: 100, title: "Browser Cache Poisoning", severity: AlertSeverity.Medium, state: AlertState.Triage, age: "1 day" }
]

export default SAMPLE_ALERTS
